### ISSUE TITLE
How to stop downloading without clean temporary files

### ISSUE THREAD

**Issue by samilywang** [vaenow/cordova-plugin-pause-resume-download#3]
In your [demo](https://github.com/vaenow/cordova-plugin-pause-resume-download-demo), I find that you use `window.location.reload()`  to stop downloading. In this way, Cordova will not clean the partly downloaded file. Is there any other way to get the same effect? (I don't think reload the page is a good idea.)

There is an official interface `abort()`, but it will clean the partly downloaded file.

**Comment by vaenow** [comment]
Just try `abort()`.

The method `abort()` do not clean the partly downloaded file in this plugin.

**Comment by samilywang** [comment]
OK, I find out how you do that. You use a hook script to do some modification to the native source file, remove the clean job when abort the download task.  I also find [the relevant issue](https://issues.apache.org/jira/browse/CB-8471) in [Apache Cordova issue tracker](https://issues.apache.org/jira/browse/CB-11456?jql=project%20%3D%20CB%20AND%20status%20in%20(Open%2C%20%22In%20Progress%22%2C%20Reopened)%20AND%20resolution%20%3D%20Unresolved%20AND%20component%20%3D%20%22Plugin%20File%20Transfer%22%20ORDER%20BY%20priority%20DESC%2C%20summary%20ASC%2C%20updatedDate%20DESC), but they seem to be not interested in resolving this issue.  Maybe they think cleaning the partly file when something goes wrong is simple and tidy?

After all, thanks for pointing out how to resume downloading.
